### ISSUE TITLE
Web Crawler using java

### ISSUE THREAD

**Issue by manishghusinga** [sitespeedio/crawler#15]
I am developing a project "Web Based Crawler for Data Extraction From Research Publication Databases".
please guide me to develop this project

**Comment by soulgalore** [comment]
Hey @manixx22 ,
we don't use the Java crawler anymore. It works but it can be memory heavy, it depends on how much data you want to crawl. We moved away to https://github.com/cgiffard/node-simplecrawler instead that has kind of same functionality and maybe can be something for you too.

All the best
Peter
